### หมายเหตุ: ทุก Request ต้องมีการ Login ก่อนเพื่อให้มี Cookie ส่งไป
### (หรือถ้ายังไม่มีระบบ Login ให้เพื่อนช่วยทำ Middleware จำลอง req.user มาให้ก่อน)

### ดึงข้อมูลตะกร้า
GET http://localhost:7777/api/cart/

### เพิ่มสินค้าลงตะกร้า 
POST http://localhost:7777/api/cart/add
Content-Type: application/json

{
  "userId": "user_123",
  "productId": "6a17c381d7b9296b299277da", 
  "quantity": 1
}

### อัปเดตจำนวนสินค้า
PUT http://localhost:7777/api/cart/update
Content-Type: application/json

{
  "productId": "6a0d57f760d284590d602fa9", 
  "quantity": 5
}

### ลบสินค้า 1 ชิ้นออกจากตะกร้า
DELETE http://localhost:7777/api/cart/remove/6a0d57f760d284590d602fa9

### ล้างตะกร้าทั้งหมด
DELETE http://localhost:7777/api/cart/clear