### 1. Login ก่อนเพื่อรับ Cookie (สำหรับ User)
# @name login
POST http://localhost:7777/api/auth/login
Content-Type: application/json

{
  "email": "admintest2@example.com",
  "password": "password1234"
}

### ------------------------------------------------------------
### หมายเหตุ: Request ด้านล่างนี้จะทำงานได้เมื่อมี Cookie จาก Login สำเร็จเท่านั้น
### ------------------------------------------------------------

### 2. ดูตะกร้าสินค้า (Get Cart)
GET http://localhost:7777/api/cart/

### 3. เพิ่มสินค้าลงตะกร้า (Add Item)
# Logic: บวกเพิ่มจากของเดิม (Increment: Current + New)
POST http://localhost:7777/api/cart/add
Content-Type: application/json

{
  "productId": "6a1685fc96d193295d2a496a", 
  "quantity": 1
}

### 3. เพิ่มสินค้าลงตะกร้า (Add Item)
# Logic: บวกเพิ่มจากของเดิม (Increment: Current + New)
POST http://localhost:7777/api/cart/add
Content-Type: application/json

{
  "productId": "6a17c381d7b9296b299277da", 
  "quantity": 1
}


### 4. อัปเดตจำนวนสินค้า (Update Item)
# Logic: แทนที่ด้วยจำนวนที่ระบุ (Set: Replace with New Value)
PATCH http://localhost:7777/api/cart/update
Content-Type: application/json

{
  "productId": "6a1685fc96d193295d2a496a", 
  "quantity": 1
}


### 4. อัปเดตจำนวนสินค้า (Update Item)
# Logic: แทนที่ด้วยจำนวนที่ระบุ (Set: Replace with New Value)
PATCH http://localhost:7777/api/cart/update
Content-Type: application/json

{
  "productId": "6a17c381d7b9296b299277da", 
  "quantity": 1
}

### 5. ลบสินค้า 1 ชิ้นออกจากตะกร้า (Remove Item)
DELETE http://localhost:7777/api/cart/remove/6a1685fc96d193295d2a496a

### 6. ล้างตะกร้าทั้งหมด (Clear Cart)
DELETE http://localhost:7777/api/cart/clear
