### Get my address
GET http://localhost:7777/api/users/me/address

###

### Create or update my address
PUT http://localhost:7777/api/users/me/address
Content-Type: application/json

{
  "recipientName": "Receiver Name",
  "phone": "0812345678",
  "street": "123 ถนนสุขุมวิท",
  "district": "วัฒนา",
  "province": "กรุงเทพมหานคร",
  "postcode": "10110"
}