export const fakeAdminDashboard = {
  stats: {
    totalSales: 8624.5,
    orderCount: 124,
    itemSold: 156,
    averageOrderValue: 69.55,
  },
  salesChart: [
    { label: "Mon", sales: 980 },
    { label: "Tue", sales: 1124.5 },
    { label: "Wed", sales: 860 },
    { label: "Thu", sales: 1340 },
    { label: "Fri", sales: 1210 },
    { label: "Sat", sales: 1490 },
    { label: "Sun", sales: 1620 },
  ],
  productBreakdown: [
    { label: "Visual Art", value: 68, sold: 68 },
    { label: "Craft & Handmade", value: 52, sold: 52 },
    { label: "Music & Sound", value: 36, sold: 36 },
  ],
  recentOrders: [
    {
      id: "order_001",
      orderNo: "CM-20191",
      product: "Golden Bloom Poster",
      artist: "Asha Studio",
      customer: "Sarah Jenkins",
      items: 1,
      date: "2026-03-12T10:00:00.000Z",
      price: 1250,
      status: "COMPLETED",
      courier: "Kerry Express",
      trackingNumber: "KRX128640591TH",
      image: "https://example.com/product.jpg",
    },
    {
      id: "order_002",
      orderNo: "CM-20192",
      product: "Clay Moon Vase",
      artist: "Mira Form",
      customer: "Daniel Lee",
      items: 2,
      date: "2026-03-13T09:30:00.000Z",
      price: 2450,
      status: "RECEIVABLE",
      courier: "Flash Express",
      trackingNumber: "FEX908172635TH",
      image: "https://example.com/product-2.jpg",
    },
  ],
};
